fieldLayouts:
  8999aac9-999f-4993-8011-d10926006451:
    tabs:
      -
        elements:
          -
            fieldUid: 4ea70baa-9a1d-40e0-a914-86a66466db8b
            instructions: 'This says ''Contact'' usually'
            label: 'Contact Column Title'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b87ba3ad-b826-4bf4-b3ae-33d62198354a
            instructions: 'This says Privacy Policy or something similar'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d96fde9e-dbad-4177-a783-a327a88780c8
            instructions: "info@seekult.de or something similar, can have line breaks to split information\r\n"
            label: 'Contact Section Text'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: aa05c3e1-bf32-46dd-bdcb-042ee51b9013
            instructions: 'This is where the privacy policy content goes'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Footer Content'
        sortOrder: 1
handle: footerContent
name: 'Footer Content'
