fieldLayouts:
  202eca75-4ad7-469b-9f2f-d018b34d91d9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: artists
hasUrls: true
name: Artists
settings:
  path: '@webroot/assets/artists'
sortOrder: 1
type: craft\volumes\Local
url: '@web/assets/artists'
