fieldLayouts:
  b8c3ca23-754d-4798-88e3-701e4a40ceb5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: generalImages
hasUrls: true
name: 'General Images'
settings:
  path: '@webroot/assets/general'
sortOrder: 2
type: craft\volumes\Local
url: '@web/assets/general'
