enableVersioning: true
handle: partners
name: Partners
propagationMethod: all
siteSettings:
  443aa2a3-5473-4e48-841b-13d4efd52005: # parity-group
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
