enableVersioning: true
handle: talks
name: Talks
propagationMethod: all
siteSettings:
  443aa2a3-5473-4e48-841b-13d4efd52005: # parity-group
    enabledByDefault: true
    hasUrls: true
    template: talks/_entry
    uriFormat: talks
type: single
