fieldLayouts:
  5b35ac58-a06a-44b8-ac97-a2ecda8a462a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7c0423eb-e4c4-45d3-a2f3-5f47a1eddee8
            instructions: 'Künstler*innen'
            label: 'Artists Title'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: program
hasTitleField: true
name: Program
section: 38d8321a-e121-4998-ad23-3a3594ca4ad1
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
