contentColumnType: text
fieldGroup: e832593f-a414-44f1-87fd-cdbb1026b456 # Group
handle: groupCurrentMembers
instructions: 'Please add a new line after each member.'
name: 'Current Members'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
