contentColumnType: string(255)
fieldGroup: cd8ebbf8-cbf5-4613-92dd-7841c73ddbdb # Event
handle: linkToEvent
instructions: ''
name: 'Link to Event'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
