contentColumnType: string(255)
fieldGroup: 27b1f273-b557-4701-a615-b667df1d5da6 # Partner
handle: partnerWebsite
instructions: ''
name: 'Partner Website'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
