contentColumnType: text
fieldGroup: cd8ebbf8-cbf5-4613-92dd-7841c73ddbdb # Event
handle: speakers
instructions: ''
name: Speakers
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
