fieldLayouts:
  54dcd706-63cf-4f95-a223-3343f53b59b0:
    tabs:
      -
        elements:
          -
            fieldUid: b700e7fd-5299-4373-9f2c-92b725bcb814 # Event Heading Small Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 775c922e-ce5b-4ee1-b53d-f8e73683d8b5 # Start Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 1acfc1cf-30df-41ed-9310-5d2e9bf6052f # End time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 975c334d-e7fe-4f3b-96df-cee13263acd7 # Link to Event
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 34b5621a-bcd7-4037-b537-7069dddcb513 # Description
            instructions: 'This is the field that is shown when you click an event and expand it.'
            label: Description
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdf01060-a9ad-42af-8d96-13c28f616f5f # Speakers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 2a0ebe42-d3d2-46e7-bb92-b605a8b36cd6 # Online or Offline
            instructions: 'Select if the event is happening online or not. This Styles it accordingly on the website.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: events
hasTitleField: true
name: Events
section: 9386ce07-ee4b-4661-ae65-70beb33ed42f # Season
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
