fieldLayouts:
  d30362d3-a15e-4bc7-84f9-638a5c3c2381:
    tabs:
      -
        elements:
          -
            fieldUid: 775c922e-ce5b-4ee1-b53d-f8e73683d8b5 # Start Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 75
          -
            fieldUid: 34b5621a-bcd7-4037-b537-7069dddcb513 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: schedule
hasTitleField: true
name: Schedule
section: 3cb18b6b-b32e-483a-8784-eb3af346e147 # Schedule
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
