field: 27a35231-c399-49a7-b2c4-c699cb91e4a4
fieldLayouts:
  79ec2ef2-5916-4389-9b7f-53226c780467:
    tabs:
      -
        elements:
          -
            fieldUid: 373318d4-eeb8-4c7f-95a1-92330e5c8797
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  373318d4-eeb8-4c7f-95a1-92330e5c8797:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:091e426a-d9d6-413e-8543-51253f999bbd'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:091e426a-d9d6-413e-8543-51253f999bbd'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
