field: f555c474-9ab1-495c-98c1-a796fee1d571
fieldLayouts:
  9816894d-1fcb-44ab-b9b3-c05f68f0a74f:
    tabs:
      -
        elements:
          -
            fieldUid: 7e5ea495-6c21-4a86-aa57-a5a50292b791
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: a75ae900-be74-4b0c-ba65-35523d63be0e
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b06364a8-6bda-4ffe-8fc6-53a3184a31eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7e5ea495-6c21-4a86-aa57-a5a50292b791:
    contentColumnType: text
    fieldGroup: null
    handle: responseName
    instructions: 'The name of the person who submitted the response goes here'
    name: 'response Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a75ae900-be74-4b0c-ba65-35523d63be0e:
    contentColumnType: text
    fieldGroup: null
    handle: responseTitle
    instructions: 'Student, Professor, etc.'
    name: 'Response Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b06364a8-6bda-4ffe-8fc6-53a3184a31eb:
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: ''
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:091e426a-d9d6-413e-8543-51253f999bbd'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1f98a719-0993-457f-9b76-9ef0a090c0cd'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: photo
name: 'Photo Response'
sortOrder: 1
