field: f555c474-9ab1-495c-98c1-a796fee1d571
fieldLayouts:
  3445c911-c580-4af5-8309-1a3363d7a952:
    tabs:
      -
        elements:
          -
            fieldUid: a1915a93-9a83-4fd3-8d21-536e77cdc98d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: df37e05f-5a37-4c55-9df6-38586a28c70c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: ca00465c-ed5a-4349-8603-59693d959fd1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a1915a93-9a83-4fd3-8d21-536e77cdc98d:
    contentColumnType: text
    fieldGroup: null
    handle: responseName
    instructions: ''
    name: 'Response Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ca00465c-ed5a-4349-8603-59693d959fd1:
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:091e426a-d9d6-413e-8543-51253f999bbd'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:091e426a-d9d6-413e-8543-51253f999bbd'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  df37e05f-5a37-4c55-9df6-38586a28c70c:
    contentColumnType: text
    fieldGroup: null
    handle: responseTitle
    instructions: ''
    name: 'Response Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: 'Video Response'
sortOrder: 3
