contentColumnType: text
fieldGroup: 3e28f92e-8dc6-40e3-a85f-9850b24f8b17
handle: artistInterventionName
instructions: 'This is the name of the intervention/event, if existing'
name: 'Artist Intervention Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
