contentColumnType: text
fieldGroup: 84ba945f-f1bb-4d48-9662-0293508492b4
handle: artistSectionTitle
instructions: ''
name: 'Artist Section Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
