contentColumnType: datetime
fieldGroup: 51c9fc81-4cb7-4353-bcb7-d661c8fcff66
handle: homeDate
instructions: ''
name: 'Home Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
