contentColumnType: string
fieldGroup: 2d3b5721-b65f-462e-949e-4fad297bfbd1
handle: logbookResponses
instructions: 'This is where the responses for each log will be added :)'
name: 'Logbook Responses'
searchable: false
settings:
  contentTable: '{{%matrixcontent_logbookresponses}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
