enableVersioning: true
handle: hygiene
name: Hygiene
propagationMethod: all
siteSettings:
  6e717b50-587c-4af5-b487-e10a9fcb59ef:
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: hygiene
type: single
