enableVersioning: true
handle: logbook
name: Logbook
propagationMethod: all
siteSettings:
  6e717b50-587c-4af5-b487-e10a9fcb59ef:
    enabledByDefault: true
    hasUrls: true
    template: logbook/_entry
    uriFormat: logbook
type: single
