enableVersioning: true
handle: program
name: Program
propagationMethod: all
siteSettings:
  6e717b50-587c-4af5-b487-e10a9fcb59ef:
    enabledByDefault: true
    hasUrls: true
    template: program/_entry
    uriFormat: program
type: single
