fieldLayouts:
  c85ba53a-655c-4d8f-abe5-b5bb6550222f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: bc105ad2-0791-4683-9aee-939f1592ab59
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: artistLocation
name: 'Artist Location'
siteSettings:
  6e717b50-587c-4af5-b487-e10a9fcb59ef:
    hasUrls: true
    template: artist/_category
    uriFormat: 'artist/category/{slug}'
structure:
  maxLevels: 1
  uid: a248a8f0-a1a1-4007-805d-88084c96d5d8
